<?php

namespace App\Enums\V2\Admin\Popular;

enum CodeErrorsEnum: string
{
    case CREATE_PLANNING_EXISTE = 'E0001';
    case UPDATE_PLANNING_EXISTE = 'E0002';
    case PLANNING_NOT_FOUND = 'E0003';
    case INSUFFICIENT_SOLDE = 'E0004';
    case PLANNING_HAS_SESSION = 'E0005';
    case PLANNING_HAS_SESSION_OR_HAS_ALREADY_PROPOSITION = 'E0006';
    case PROPOSITION_HAS_ALREADY_ACTIVATED = 'E0007';

    case ANNULATION_DOSNT_ANNULABLE = 'E0008';
    case ANNULATION_ALREADY_JUSTIFIED = 'E0009';
}
